#!/bin/sh
selection=$(echo -e "Channel \n Video" | dmenu -p "search:")
if [ $selection == "Channel" ]
then
	echo "" | dmenu -p "Search:"| xargs -I{} ytfzf -D --type=channel {}
else
	echo "" | dmenu -p "Search:"| xargs -I{} ytfzf -D {}
fi

